<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <RootNamespace>Delta.Engine.Generation.Core</RootNamespace>
    <AssemblyName>DeltaEngine.Generation.Core</AssemblyName>
    <PackageId>DeltaEngine.Generation.Core</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
